version: '3.8'

services:
  codexy-api-prod:
    container_name: codexy-api-prod
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "5400:8080"
    networks:
      - codexy-network

networks:
  codexy-network:
    external: true